{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "541d48d2",
   "metadata": {},
   "source": [
    "## Multiplayer Proxy Failure"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4b04b8cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import module\n",
    "import numpy as np\n",
    "import csv\n",
    "from joblib import Parallel, delayed\n",
    "from itertools import product\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings(\"error\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b3cb8f1e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "14acfd41",
   "metadata": {},
   "source": [
    "## Useful functions\n",
    "\n",
    "Comparatively to the last one: goal is always the same, no inverse, actions are always the same, steps after discard is always the same, all parameters are in the ESN"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3de570cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "def compute_proxy_nodes_from_esn(esn, trials=10):  \n",
    "    \"\"\"\n",
    "    Compute proxy nodes from an Echo State Network (ESN) by running trials with random agent actions.\n",
    "    The function calculates the average values of the goal node and the proxy nodes based on the ESN's states.\n",
    "    \"\"\"\n",
    "\n",
    "    num_nodes = esn.n\n",
    "    possible_nodes =  [i for i in range(num_nodes) if i not in esn.action_nodes and i not in esn.goal]\n",
    "    run_data_base = np.zeros((trials, num_nodes)) \n",
    "    avg_goal_values = []\n",
    "    avg_proxy_values = []\n",
    "    for k in range(trials):\n",
    "        # Generate random agent actions\n",
    "        action_node_values = np.random.choice([-1.0, 0.0, 1.0], size=len(esn.action_nodes))\n",
    "        \n",
    "        # Run the ESN with the random agent actions\n",
    "        states = esn.run( agent_values=action_node_values)\n",
    "        data_run =  np.mean(states[esn.proxy_discard: esn.proxy_discard + esn.measure_time, :], axis=0)\n",
    "        data_run[esn.goal] = np.mean(states[esn.goal_discard: esn.goal_discard+ esn.measure_time, esn.goal], axis=0)\n",
    "        run_data_base[k] = data_run\n",
    "        # Compute the average values \n",
    "        avg_goal_values.append(np.mean(states[:, esn.goal], axis=0))\n",
    "\n",
    "    correlations = np.mean(np.corrcoef(run_data_base, rowvar= False)[:, esn.goal], axis=1)#here the runs are on axis 0 and the nodes on axis 1\n",
    "\n",
    "    bin_edges = np.linspace(-1, 1, 100)\n",
    "    bin_indices =  np.histogram(correlations, bin_edges)[0] \n",
    "    bin_indices = [int(k) for k in  bin_indices]\n",
    "    # check if there are nan values in correlations\n",
    "    if np.isnan(correlations).any():\n",
    "        raise ValueError(\"NaN values found in correlations\")\n",
    "        \n",
    "\n",
    "    # Sort nodes by correlation in descending order and select top nodes\n",
    "    sorted_indices = [k for k in np.argsort(correlations)[::-1 ] if k in possible_nodes]\n",
    "    proxy_nodes = sorted_indices[:1]\n",
    "    avg_proxy_values.append(np.mean(run_data_base[:, proxy_nodes], axis=0))\n",
    "    goal_value = np.mean(avg_goal_values)\n",
    "    proxy_value = np.mean(avg_proxy_values)\n",
    "    #print(bin_indices)\n",
    "\n",
    "    return proxy_nodes, goal_value, proxy_value, correlations, bin_indices"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "ccfc3505",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "def optimize_node(esn,  trials, proxy_nodes, is_goal=False):\n",
    "\n",
    "    n = esn.n \n",
    "    num_action_nodes = len(esn.action_nodes)\n",
    "    start_time = esn.proxy_discard*(not is_goal) + esn.goal_discard*is_goal\n",
    "    end_time = start_time + esn.measure_time\n",
    "    # define function to test an agent action \n",
    "    def test_agent_action(agent_action, action_value):\n",
    "        \"\"\"\n",
    "        Test the average value of an action node if all other nodes are set to random values\n",
    "        \"\"\"\n",
    "        run_data_base = [0 for i in range(trials)]\n",
    "        proxy_samples    = np.asarray([])\n",
    "        goal_samples    = np.asarray([])\n",
    "        actionVALS = []\n",
    "        for j in range(trials): \n",
    "            action_node_values = np.random.choice([-1.0, 0.0, 1.0], size=len(esn.action_nodes))\n",
    "            action_node_values[agent_action] = action_value\n",
    "            # REMOVE actionVALS.append(action_node_values)\n",
    "            states = esn.run(agent_values=action_node_values)\n",
    "            proxy_samples = np.concatenate((proxy_samples,np.mean(states[start_time:end_time, proxy_nodes], axis=0)))\n",
    "            goal_samples = np.concatenate((goal_samples,np.mean(states[esn.goal_discard:esn.goal_discard+esn.measure_time, esn.goal], axis=0)))\n",
    "        try:\n",
    "            correl_node_goal = np.corrcoef(proxy_samples, goal_samples)[0, 1]\n",
    "        except RuntimeWarning:\n",
    "            correl_node_goal = -np.inf\n",
    "        return np.mean(proxy_samples), np.mean(goal_samples), correl_node_goal\n",
    "    max_proxy_value = -1\n",
    "    goal_value_on_max_proxy = -1\n",
    "    correlation_on_max_proxy = 0\n",
    "    for i in range(num_action_nodes):\n",
    "        for val in [-1.0, 1.0]:\n",
    "            proxy_value, goal_value, correl_node_goal = test_agent_action(i, val)\n",
    "            if proxy_value > max_proxy_value:\n",
    "                max_proxy_value = proxy_value\n",
    "                goal_value_on_max_proxy = goal_value\n",
    "                correlation_on_max_proxy = correl_node_goal\n",
    "\n",
    "    return (goal_value_on_max_proxy, max_proxy_value, correlation_on_max_proxy)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "6210b396",
   "metadata": {},
   "outputs": [],
   "source": [
    "def parallel_compute_proxy_failure(param_ESN):\n",
    "    esn = module.EchoStateNetwork(param_ESN['n'],  spectral_radius=param_ESN['spectral_radius'], alpha = param_ESN['alpha'], \n",
    "                                avg_number_of_edges=param_ESN['avg_number_of_edges'], proxy_discard=param_ESN['proxy_discard'],\n",
    "                                goal_discard=param_ESN['goal_discard'], measure_time=param_ESN['measure_time'])\n",
    "\n",
    "    proxy_nodes, goal_base, proxy_base, correlations, bin_indices = compute_proxy_nodes_from_esn(esn, trials=param_ESN['trials'])\n",
    "    correlation_base = np.mean(correlations[proxy_nodes])\n",
    "    correlation_std = np.std(correlations)\n",
    "    maxed_goal_value, maxed_proxy_value, correlation_on_max_proxy = optimize_node(esn,  param_ESN['trials'], proxy_nodes)\n",
    "    optimal_goal_value, optimal_proxy_value, correlation_on_optimal_proxy =  optimize_node(esn,  param_ESN['trials'], esn.goal, is_goal=True)\n",
    "    to_return = {\n",
    "        'correlation_std': correlation_std,\n",
    "        'maxed_goal_value': maxed_goal_value,\n",
    "        'goal_base': goal_base,\n",
    "        'maxed_proxy_value': maxed_proxy_value,\n",
    "        'correlation_on_max_proxy': correlation_on_max_proxy,\n",
    "        'correlation_base': correlation_base,\n",
    "        'optimal_goal_value': optimal_goal_value,\n",
    "        'optimal_proxy_value': optimal_proxy_value,\n",
    "        'correlation_on_optimal_proxy': correlation_on_optimal_proxy,\n",
    "        'bin_indices_on_base_correlation': bin_indices,\n",
    "        'proxy_base': proxy_base\n",
    "    }\n",
    "    return to_return"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "e88c04f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def parallel_compute_correlation(param_exp,param_ESN):\n",
    "    esn = module.EchoStateNetwork(param_ESN['n'],  spectral_radius=param_ESN['spectral_radius'], alpha = param_ESN['alpha'], \n",
    "                                avg_number_of_edges=param_ESN['avg_number_of_edges'], discard=param_ESN['discard'])\n",
    "    param_exp['esn'] = esn\n",
    "    # Compute proxy nodes\n",
    "    proxy_nodes, goal_base, proxy_base, correlations = compute_proxy_nodes_from_esn(esn, trials=param_ESN['trials'])\n",
    "    correlations = list(correlations)\n",
    "    to_return = {\n",
    "        'correlations': correlations,\n",
    "    } \n",
    "    return to_return"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b396b573",
   "metadata": {},
   "source": [
    "## Main loop to generate experiments"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "55454be9",
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_experimental_data(filename, param_grid, number_of_instances, intention = 'a', skip_to = 0):\n",
    "    np.random.seed(0)\n",
    "    # creates a list of the parameters that will vary\n",
    "    varying_params = [a for a in param_grid.keys() if len(param_grid[a]) > 1]\n",
    "    # Create a list of all combinations of parameters\n",
    "\n",
    "    param_combinations = list(product(*param_grid.values()))\n",
    "    print(\"param_combinations\", len(param_combinations))\n",
    "    # Create a list of parameter names\n",
    "    param_names = list(param_grid.keys())\n",
    "    # Loop through all combinations of parameters\n",
    "\n",
    "    param_range = range(len(param_combinations))\n",
    "    if skip_to > 0:\n",
    "        param_range = range(skip_to-1, skip_to )\n",
    "        print(\"skipping to\", skip_to, \"out of\", len(param_combinations))\n",
    "    print(filename, intention)\n",
    "    with open(filename,intention) as fd:\n",
    "        fieldnames = ['correlation_std', 'bin_indices_on_base_correlation',\n",
    "                      'maxed_goal_value','goal_base',\n",
    "                      'maxed_proxy_value','proxy_base',\n",
    "                      'correlation_on_max_proxy','correlation_base',\n",
    "                      'optimal_goal_value','optimal_proxy_value','correlation_on_optimal_proxy'] \n",
    "        writer = csv.DictWriter(fd, fieldnames=param_names + fieldnames)\n",
    "        if intention == 'w':\n",
    "            writer.writeheader()\n",
    "        for k in param_range:\n",
    "\n",
    "            params = param_combinations[k]\n",
    "            # Create a dictionary of parameters\n",
    "            param_ESN = dict(zip(param_names, params))\n",
    "            param_ESN['trials'] = 50\n",
    "            name = 'ESN'+ \"\".join(['_'+a +'_'+ str(b) for (a,b) in list(zip(param_names, params)) if a in varying_params])\n",
    "            print(\"instance\", k+1, \"out of \", len(param_combinations), \"name\", name)\n",
    "            \n",
    "            delta_goal_values,delta_optimal_goals,delta_proxy_correlations,List_output = [], [], [], []\n",
    "            # run the parallel computation of proxy nodes\n",
    "            List_output = Parallel(n_jobs=-1, return_as='list')(\n",
    "                [delayed(parallel_compute_proxy_failure)(param_ESN) for _ in range(number_of_instances)]\n",
    "            )\n",
    "            #print(\"List_output\", List_output)\n",
    "            for temp_dict in List_output:\n",
    "                writer.writerow(param_ESN | temp_dict)\n",
    "            fd.flush()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "7e8f090b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "param_combinations 256\n",
      "data_file_dump_2.csv w\n",
      "instance 1 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 2 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 3 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 4 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 5 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 6 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 7 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 8 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 9 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_2_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 10 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 11 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 12 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 13 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_3_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 14 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 15 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 16 out of  256 name ESN_n_120_goal_discard_50_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 17 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 18 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 19 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 20 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 21 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 22 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 23 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 24 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 25 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 26 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 27 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 28 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 29 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 30 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 31 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 32 out of  256 name ESN_n_120_goal_discard_150_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 33 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 34 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 35 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 36 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 37 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 38 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 39 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 40 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 41 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 42 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 43 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 44 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 45 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 46 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 47 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 48 out of  256 name ESN_n_120_goal_discard_250_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 49 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 50 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 51 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 52 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 53 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 54 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 55 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 56 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 57 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 58 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 59 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 60 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 61 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 62 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 63 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 64 out of  256 name ESN_n_120_goal_discard_450_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 65 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 66 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 67 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 68 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 69 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 70 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 71 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 72 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 73 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 74 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 75 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 76 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 77 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 78 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 79 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 80 out of  256 name ESN_n_256_goal_discard_50_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 81 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 82 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 83 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 84 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 85 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 86 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 87 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 88 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 89 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 90 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 91 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 92 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 93 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 94 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 95 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 96 out of  256 name ESN_n_256_goal_discard_150_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 97 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 98 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 99 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 100 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 101 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 102 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 103 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 104 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 105 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 106 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 107 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 108 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 109 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 110 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 111 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 112 out of  256 name ESN_n_256_goal_discard_250_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 113 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 114 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 115 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 116 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 117 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 118 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 119 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 120 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 121 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 122 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 123 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 124 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 125 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 126 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 127 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 128 out of  256 name ESN_n_256_goal_discard_450_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 129 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 130 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 131 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 132 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 133 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 134 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 135 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 136 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 137 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 138 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 139 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 140 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 141 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 142 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 143 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 144 out of  256 name ESN_n_512_goal_discard_50_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 145 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 146 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 147 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 148 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 149 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 150 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 151 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 152 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 153 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 154 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 155 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 156 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 157 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 158 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 159 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 160 out of  256 name ESN_n_512_goal_discard_150_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 161 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 162 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 163 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 164 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 165 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_1\n",
      "instance 166 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 167 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 168 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 169 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 170 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 171 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 172 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 173 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 174 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 175 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 176 out of  256 name ESN_n_512_goal_discard_250_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 177 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 178 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 179 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 180 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 181 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 182 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 183 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 184 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 185 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_2_avg_number_of_edges_1\n",
      "instance 186 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 187 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 188 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 189 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_3_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 190 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 191 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 192 out of  256 name ESN_n_512_goal_discard_450_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 193 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 194 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 195 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 196 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 197 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 198 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 199 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 200 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 201 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_2_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 202 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 203 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 204 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 205 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_3_avg_number_of_edges_1\n",
      "instance 206 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 207 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 208 out of  256 name ESN_n_1024_goal_discard_50_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 209 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1_avg_number_of_edges_1\n",
      "instance 210 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 211 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 212 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 213 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 214 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 215 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 216 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 217 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_2_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 218 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 219 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 220 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 221 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_3_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 222 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 223 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 224 out of  256 name ESN_n_1024_goal_discard_150_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 225 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 226 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 227 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 228 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 229 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 230 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 231 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 232 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 233 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_2_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 234 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 235 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 236 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 237 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_3_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 238 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_3_avg_number_of_edges_2\n",
      "instance 239 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 240 out of  256 name ESN_n_1024_goal_discard_250_spectral_radius_3_avg_number_of_edges_8\n",
      "instance 241 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 242 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1_avg_number_of_edges_2\n",
      "instance 243 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1_avg_number_of_edges_4\n",
      "instance 244 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1_avg_number_of_edges_8\n",
      "instance 245 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 246 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_2\n",
      "instance 247 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_4\n",
      "instance 248 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_1.5_avg_number_of_edges_8\n",
      "instance 249 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_2_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 250 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_2_avg_number_of_edges_2\n",
      "instance 251 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_2_avg_number_of_edges_4\n",
      "instance 252 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_2_avg_number_of_edges_8\n",
      "instance 253 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_3_avg_number_of_edges_1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 254 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_3_avg_number_of_edges_2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[:, None]\n",
      "/home/paulbanse/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide\n",
      "  c /= stddev[None, :]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "instance 255 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_3_avg_number_of_edges_4\n",
      "instance 256 out of  256 name ESN_n_1024_goal_discard_450_spectral_radius_3_avg_number_of_edges_8\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "use_baby_params = False\n",
    "\n",
    "data_file_dump = 'data_file_dump_2.csv'\n",
    "number_of_instances = 40\n",
    "param_grid = {\n",
    "    'n': [120, 256, 512, 1024], \n",
    "    'trials': [50],\n",
    "    'proxy_discard': [50],\n",
    "    'goal_discard': [50, 150, 250, 450],\n",
    "    'measure_time': [50],\n",
    "    'spectral_radius': [1, 1.5, 2, 3],\n",
    "    'alpha': [0.1],\n",
    "    \"avg_number_of_edges\": [1, 2, 4, 8]\n",
    "}\n",
    "\n",
    "param_grid_second_computer = {\n",
    "    'n': [ 2048], \n",
    "    'trials': [50],\n",
    "    'proxy_discard': [50],\n",
    "    'goal_discard': [50, 150, 250, 450],\n",
    "    'measure_time': [50],\n",
    "    'spectral_radius': [1, 1.5, 2, 3],\n",
    "    'alpha': [0.1],\n",
    "    \"avg_number_of_edges\": [1, 2, 4, 8]\n",
    "}\n",
    "if use_baby_params:\n",
    "    data_file_dump = 'data_file_dump_baby.csv'\n",
    "    number_of_instances = 1\n",
    "    param_grid = {\n",
    "        'n': [256], \n",
    "        'trials': [50],\n",
    "        'proxy_discard': [50],\n",
    "        'goal_discard': [100],\n",
    "        'measure_time': [50],\n",
    "        'spectral_radius': [1.5],\n",
    "        'alpha': [0.1],\n",
    "        \"avg_number_of_edges\": [3]\n",
    "    }\n",
    "\n",
    "generate_experimental_data(data_file_dump, param_grid, number_of_instances, intention = 'w', skip_to = 0 )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5271c4b4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/paulbanse/backup pc/projet_gens/Wolfram/Pietro's model/Clean_version\n"
     ]
    }
   ],
   "source": [
    "import os \n",
    "\n",
    "print(os.getcwd())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
